### ISSUE TITLE
Show more info on output

### ISSUE THREAD

**Issue by MartenBE** [svdimchenko/ski-lint#1]
Hi, I am using this to find tricky non-ASCII characters when copying from powerpoint into markdown. When doing this, I noticed that a lot of the non-ASCII codes are non-printable. This tool detects and finds them, but makes it hard to find out where the non-ASCII chars are, as they are not word-related. I was wondering if the output could be changed so it shows the file name, line number and character number?

The output of ski-lint:

![Screenshot_20240827_161554](https://github.com/user-attachments/assets/4ee60998-43eb-49fe-8ab3-8d1defcba8f8)

More comfortable output by using bash commands:

![Screenshot_20240827_161607](https://github.com/user-attachments/assets/e453f024-9d6c-4933-9c9a-0e27ed3dc9e6)

More comfortable output using self made python script before I found this repo:

![Screenshot_20240827_161316](https://github.com/user-attachments/assets/4c25b41c-42bd-4cf4-80a5-8ac59efbb066)

**Comment by svdimchenko** [comment]
hi there @MartenBE ! It's great that this tool is helpful!
Could you open a PR with more clear output implementation ?

**Comment by MartenBE** [comment]
Yes, I've opened a PR in https://github.com/svdimchenko/ski-lint/pull/2 :)

**Comment by svdimchenko** [comment]
> Yes, I've opened a PR in #2 :)

great job done @MartenBE, many thanks for that. I've pulished the new package version to PyPi with your changes applied: https://pypi.org/project/ski-lint/.

**Comment by MartenBE** [comment]
No problem, thanks to follow it up. I'll probably add a PR soon for allowed exceptions :)
